version: '3'
services:
  node:
    build: 
      context: .
    environment:
      - NODE_ENV=production
    volumes:
      - "./:/usr/src/app"
    command: sh -c "cd react-todo && npm start"
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    tty: true
